# Generated by Django 5.2.7 on 2025-12-17 17:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Obra Social',
                'verbose_name_plural': 'Obras Sociales',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='especialidad',
            name='duracion_turno',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='obra_social',
            field=models.CharField(blank=True, help_text='Campo legacy - usar obra_social_obj', max_length=100),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('activo', 'Activo'), ('en_atencion', 'En Atención'), ('atendido', 'Atendido'), ('cancelado_paciente', 'Cancelado por Paciente'), ('cancelado_medico', 'Cancelado por Médico'), ('ausente', 'Ausente'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}$', 'Ingrese un DNI válido (7-8 dígitos)')]),
        ),
        migrations.AddField(
            model_name='paciente',
            name='obra_social_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='appointments.obrasocial', verbose_name='Obra Social'),
        ),
    ]
