# Generated by Django 5.2.8 on 2025-12-17 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_eliminar_unique_together_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='appointments.medico'),
        ),
    ]
